// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7B2TSNUGrIpsrUpMTyX9ZLZm1hQ2U5-E',
    appId: '1:805098540855:web:d56494840de6c01d9e14b2',
    messagingSenderId: '805098540855',
    projectId: 'travel-9a96d',
    authDomain: 'travel-9a96d.firebaseapp.com',
    storageBucket: 'travel-9a96d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--J477JzQ_F6At-e_EbmN_sfOOEzrUno',
    appId: '1:805098540855:ios:86826658b070228f9e14b2',
    messagingSenderId: '805098540855',
    projectId: 'travel-9a96d',
    storageBucket: 'travel-9a96d.firebasestorage.app',
    iosClientId: '805098540855-2uja6jquh4q4jldj4po9r39mc06613k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelWeb',
  );

}